#!/bin/bash
echo "=== Edge Case Analysis ==="
echo ""
echo "Test 1: Invalid user (nonexistent_user)"
echo "Expected: -1"
echo "Actual: $(sed -n '1p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo ""
echo "Test 2: User not logged in (user1 before login)"
echo "Expected: -1"
echo "Actual: $(sed -n '3p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo ""
echo "Test 3: User logged in but no orders (user1 after login)"
echo "Expected: 0"
echo "Actual: $(sed -n '9p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo ""
echo "Test 4: User with one order (user1 after buy_ticket)"
echo "Expected: 1 + order details"
echo "Actual Count: $(sed -n '15p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo "Actual Order: $(sed -n '16p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo ""
echo "Test 5: Multiple orders with sorting (user2 with 3 orders)"
echo "Expected: 3 + 3 order lines sorted by timestamp"
echo "Actual Count: $(sed -n '23p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo "Order 1: $(sed -n '24p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo "Order 2: $(sed -n '25p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo "Order 3: $(sed -n '26p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo ""
echo "Test 6: Pending order (user3 with 2 orders, one pending)"
echo "Expected: 2 + 2 order lines (one success, one pending)"
echo "Actual Count: $(sed -n '34p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo "Order 1: $(sed -n '35p' workspace/workspace/tyler/query_order_final_actual.txt)"
echo "Order 2: $(sed -n '36p' workspace/workspace/tyler/query_order_final_actual.txt)"
