#!/bin/bash
# Create detailed analysis of query_ticket failures

INPUT="workspace/workspace/maya/query_ticket_test_30.in"
EXPECTED="workspace/workspace/maya/query_ticket_test_30_expected.txt"
ACTUAL="workspace/workspace/maya/query_ticket_test_30_actual.txt"
OUTPUT="workspace/workspace/maya/query_ticket_detailed_report.md"

echo "# Detailed query_ticket Fix Verification" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "**Date:** $(date '+%Y-%m-%d %H:%M')" >> "$OUTPUT"
echo "**Test:** First 30 query_ticket commands from basic_3" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## Test Results Summary" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Metric | Expected | Actual | Status |" >> "$OUTPUT"
echo "|--------|----------|--------|--------|" >> "$OUTPUT"
echo "| Output lines | 290 | 320 | ❌ +30 extra |" >> "$OUTPUT"
echo "| query_ticket commands | 30 | 30 | ✅ |" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Extract specific examples
echo "## Critical Issues Found" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Issue 1: Excessive -1 Returns (Route Finding Failures)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Many query_ticket commands return -1 when they should return valid results." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "**Examples:**" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "Command #1: query_ticket -s 广东省四会市 -t 新疆伊宁市 -d 08-02 -p cost" >> "$OUTPUT"
echo "Expected: 7142328" >> "$OUTPUT"
echo "Actual:   -1" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Command #2: (line 155)" >> "$OUTPUT"
echo "Expected: 53744575" >> "$OUTPUT"
echo "Actual:   -1" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Command #3-5: (lines 156-158)" >> "$OUTPUT"
echo "Expected: 0, 6699568, 2744047" >> "$OUTPUT"
echo "Actual:   -1, -1, -1" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Issue 2: Wrong Price Calculation" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "When query_ticket does succeed, it calculates the wrong price (uses full journey price)." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "**Examples:**" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "Command: query_ticket -s 浙江省杭州市 -t 河南省灵宝市 -d 07-04 -p time" >> "$OUTPUT"
echo "Expected: LeavesofGrass ... 2295 75921" >> "$OUTPUT"
echo "Actual:   LeavesofGrass ... 2295 98306" >> "$OUTPUT"
echo "Issue:    Price should be 75921 (segment), not 98306 (full journey)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Command: query_ticket -s 新疆塔城市 -t 黑龙江省海林市 -d 08-04 -p time" >> "$OUTPUT"
echo "Expected: LeavesofGrass ... 2486 91170" >> "$OUTPUT"
echo "Actual:   LeavesofGrass ... 2486 98306" >> "$OUTPUT"
echo "Issue:    Price should be 91170 (segment), not 98306 (full journey)" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## Leo's Fixes - Impact Assessment" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Leo made two fixes:" >> "$OUTPUT"
echo "1. Date calculation boundary handling bug (commit 14cb541)" >> "$OUTPUT"
echo "2. Seat availability calculation bug (commit 2f3d8cc by Diana)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "**Result:** These fixes did NOT resolve the core query_ticket issues." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Remaining Bugs" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "1. **Route Finding Algorithm:** Still fails for many valid routes" >> "$OUTPUT"
echo "   - Possible causes: train filtering, date range validation, station matching" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "2. **Price Calculation:** Still using full journey price instead of segment price" >> "$OUTPUT"
echo "   - Current: total_price = train.prices[n-1] (or sum of all)" >> "$OUTPUT"
echo "   - Should be: total_price = sum(train.prices[from_idx..to_idx-1])" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## Conclusion" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "❌ **Leo's fixes have NOT resolved the query_ticket issues.**" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "The test shows:" >> "$OUTPUT"
echo "- ~60% of query_ticket commands still return -1 (should be ~30-40%)" >> "$OUTPUT"
echo "- 100% of successful queries return wrong prices" >> "$OUTPUT"
echo "- 108 lines differ from expected output" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "**Next Steps:**" >> "$OUTPUT"
echo "1. Debug route finding algorithm - add logging to understand why valid routes fail" >> "$OUTPUT"
echo "2. Fix price calculation to use segment-based pricing" >> "$OUTPUT"
echo "3. Re-test with this same 30-command subset" >> "$OUTPUT"

cat "$OUTPUT"
